# RHEL 8 must use ansible 2.16!

infrastructure:
  hosts:
    lab-ldap-0.lab.asio:
    lab-mssql-0.lab.asio:
    lab-postgresql-0.lab.asio:

cp_ansible:
  hosts:
    lab-zookeeper-0.lab.asio:
    lab-zookeeper-1.lab.asio:
    lab-zookeeper-2.lab.asio:
    lab-kafka-0.lab.asio:
    lab-kafka-1.lab.asio:
    lab-kafka-2.lab.asio:
    lab-connect-0.lab.asio:
    lab-schema-registry-0.lab.asio:
    lab-control-center-0.lab.asio:
    lab-ksql-0.lab.asio:


k3s_lab:
  hosts:
    k3s-lab-server-0.lab.asio:
    k3s-lab-agent-0.lab.asio:
    k3s-lab-agent-1.lab.asio:

debian:
  children:
    k3s_lab:

rhel9:
  children:
    infrastructure:

rhel8:
  children:
    cp_ansible:

rhel:
  children:
    rhel8:
    rhel9: