- name: Debian 12 SOE
  hosts: debian
  become: yes
  tasks:
  - name: SOE packages
    ansible.builtin.apt:
      name: 
      - vim
      - tree
      - rsync
      - python3
      - python3-hvac
      - lshw
      - acl # to resolve : failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user 
      - prometheus-node-exporter
      - needrestart
      update_cache: yes
  - name: install authorized keys
    ansible.builtin.copy:
      dest: /home/geoff/.ssh/authorized_keys
      src: ~/homelab/ansible/roles/soe/files/authorized_keys
      owner: geoff
      group: geoff
      mode: '0644'
  - name: install chrony
    ansible.builtin.apt:
      name: chrony
      update_cache: yes
  - name: systemd chronyd
    ansible.builtin.systemd_service:
      state: started
      enabled: true
      daemon_reload: true
      name: chronyd          