- name: RHEL SOE
  hosts: all
  become: yes
  tasks:
  - name: setup epel
    ansible.builtin.dnf:
      name: epel-release
      state: present
  - name: install node exporter
    ansible.builtin.dnf:
      name: golang-github-prometheus-node-exporter
      state: present
  - name: enable node exporter
    ansible.builtin.systemd_service:
      name: "{{ prometheus_node_exporter_service }}"
      state: started
      daemon_reload: true
      enabled: true